taehyung/backend_demo/app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    #Lists pages
    url(r'^$', views.post_list, name='post_list'),
    
    #Making New
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^reply/new/$', views.reply_new, name='reply_new'),
    url(r'^corporation/new/$', views.corporation_new, name='corporation_new'),

    #Edit
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

 
]

taehyung/backend_demo/backend_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taehyung/backend_demo/app/templates/app/add_corporation.html
{% extends "app/base.html" %}

{% block content %}


{% load staticfiles%}

      <div class="container">
          <div class="col-sm-12">
              <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                <div class="form-group">
                    
                    
                    <div class="col-sm-10 col-sm-offset-1"> 
                        <h2 >Update Corporation Information</h2>
                        <br>
                        
                        <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                      
                          {{ form.as_p }}
                      
                      
                        </form>
                        <button type="submit" class="btn btn-primary btn-lg">Write Reply</button>
                    </div>
                    
                </div>                 
              </form>
          </div>
      </div>

{% endblock %}

taehyung/backend_demo/app/templates/app/add_food.html
{% extends "app/base.html" %}

{% block content %}


{% load staticfiles%}

      <div class="container">
          <div class="col-sm-12">
              <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                <div class="form-group">
                    
                    
                    <div class="col-sm-10 col-sm-offset-1"> 
                        <h2 >Food Information Edit</h2>
                        <br>
                        
                        <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                      
                          {{ form.as_p }}
                      
                      
                        </form>
                        <button type="submit" class="btn btn-primary btn-lg">Write Reply</button>
                    </div>
                    
                </div>                 
              </form>
          </div>
      </div>

{% endblock %}

taehyung/backend_demo/app/templates/app/add_reply.html
{% extends "app/base.html" %}

{% block content %}


{% load staticfiles%}

      <div class="container">
          <div class="col-sm-12">
              <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                <div class="form-group">
                    
                    
                    <div class="col-sm-10 col-sm-offset-1"> 
                        <h2 >Write Reply</h2>
                        <br>
                        
                        <form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}   
                      
                          {{ form.as_p }}
                      
                      
                        </form>
                        <button type="submit" class="btn btn-primary btn-lg">Write Reply</button>
                    </div>
                    
                </div>                 
              </form>
          </div>
      </div>

{% endblock %}

taehyung/backend_demo/app/templates/app/base.html
<a href="{% url 'app:corporation_new' %}" >로그인하면 사진등록 리다이렉션</a>

<!DOCTYPE html>
<html>
  <head>

    {% load staticfiles %}
    {% load thumbnail %}

    <meta charset="utf-8">
    <title>reply test page</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


  </head>



  <body>
      <div class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <a href="../" class="navbar-brand">Bootswatch</a>
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
              <ul class="nav navbar-nav">
 
                <li>
                  <a href="{% url 'app:post_list' %}">최신 순</a>
                </li>           
                
              </ul>
    
              <ul class="nav navbar-nav navbar-right">
                <li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>
                <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>
              </ul>
    
            </div>
          </div>
        </div>
<!--navvar end-->

{% block content %}
{% endblock %}


  <!-- 푸터 들어가는 부분 -->

  <div>
        <p class="text-center">
            <small> @Copyrighy by </small><br>
            <small><strong> Global Hackaton Jeju</strong></small><br>
        </p>
    </div>
  </body>
</html>

taehyung/backend_demo/app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}

{% load thumbnail %}

    
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-sm-10">
          <h2 class="page-header">Comments</h2>
            <section class="comment-list">
              <!-- First Comment -->
              {% for reply in reply_list %}
              <article class="row">
                <div class="col-md-2 col-sm-2 hidden-xs">
                  <figure class="thumbnail">
                    {% for corporation in corporation_list %}
                        {% if corporation.usr == reply.usr %}
                            {% if corporation.corp_logo %}
                                <img class="img-responsive" src="{{corporation.corp_logo.url}}" />
                            {% else %}
                                <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <figcaption class="text-center">{{reply.usr}}</figcaption>
                  </figure>
                </div>
                <div class="col-md-10 col-sm-10">
                  <div class="panel panel-default arrow left">
                    <div class="panel-body">
                      <header class="text-left">
                        <div class="comment-user"><i class="fa fa-user"></i><p>{{reply.usr}}</p></div>
                        <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
                      </header>
                      <div class="comment-post">
                        <p>
                          {{reply.message}}
                        </p>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-md-5 col-sm-6 star-post" align="center">
                        <span style="font-size:20px">User Grading</span>
                        <br>
                        <p>

                            {{ reply.star }}
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </p>
                        </div>
                        <div class="col-md-7 col-sm-7 image-post">
                        <div class="col-md-6 col-sm-6 before-image-post" align="center">
                        <span style="font-size:20px">Before Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.before_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                        <div class="col-md-6 col-sm-6 after-image-post" align="center">
                        <span style="font-size:20px">After Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.after_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
              </article>
              {% endfor %}
            </section>
        </div>
      </div>
      <div class="row">
        <div class="col-md-offset-8 col-md-3 col-sm-offset-8 col-sm-3">
          <div class = "button_wrap" align="center">
            <a href="{% url 'app:reply_new' %}" class="button"> Add Comments</a>
          </div>
        </div>
      </div>
    </div>
    <hr/>


    {% endblock %}
  

taehyung/backend_demo/app/templates/app/ordered_discount.html
{% extends "app/base.html" %}

{% block content %}

{% load thumbnail %}
<!--POST start-->
<div class="container">
    <div class="row">
      <div class="col-md-10 col-sm-10">
        <h2 class="page-header">Post</h2>
          <section class="comment-list">
            <!-- First Comment -->


            {% for post in discount_ordered_list %}
              <p>{{post.id}}</p>
              <p>{{post.fname}}</p>
              <p>{{post.fcontent}}</p>
              <p >start_time : {{ post.regdate }}</p>
              <p >{{post.price}}</p>
              <p>star : {{post.star}}</p>
              <p style= "font-size:40">discount percent : {{post.percent}} %</p>

              <hr>
            {% endfor %}
          </section>
      </div>
    </div>

  </div>

  <!--POST end-->
    
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-sm-10">
          <h2 class="page-header">Comments</h2>
            <section class="comment-list">
              <!-- First Comment -->
              {% for reply in reply_list %}
              <article class="row">
                <div class="col-md-2 col-sm-2 hidden-xs">
                  <figure class="thumbnail">
                    {% for corporation in corporation_list %}
                        {% if corporation.usr == reply.usr %}
                            {% if corporation.corp_logo %}
                                <img class="img-responsive" src="{{corporation.corp_logo.url}}" />
                            {% else %}
                                <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <figcaption class="text-center">{{reply.usr}}</figcaption>
                  </figure>
                </div>
                <div class="col-md-10 col-sm-10">
                  <div class="panel panel-default arrow left">
                    <div class="panel-body">
                      <header class="text-left">
                        <div class="comment-user"><i class="fa fa-user"></i><p>{{reply.usr}}</p></div>
                        <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
                      </header>
                      <div class="comment-post">
                        <p>
                          {{reply.message}}
                        </p>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-md-5 col-sm-6 star-post" align="center">
                        <span style="font-size:20px">User Grading</span>
                        <br>
                        <p>

                            {{ reply.star }}
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </p>
                        </div>
                        <div class="col-md-7 col-sm-7 image-post">
                        <div class="col-md-6 col-sm-6 before-image-post" align="center">
                        <span style="font-size:20px">Before Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.before_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                        <div class="col-md-6 col-sm-6 after-image-post" align="center">
                        <span style="font-size:20px">After Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.after_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
              </article>
              {% endfor %}
            </section>
        </div>
      </div>
      <div class="row">
        <div class="col-md-offset-8 col-md-3 col-sm-offset-8 col-sm-3">
          <div class = "button_wrap" align="center">
            <a href="{% url 'app:reply_new' %}" class="button"> Add Comments</a>
          </div>
        </div>
      </div>
    </div>
    <hr/>


    {% endblock %}
  

taehyung/backend_demo/app/templates/app/ordered_star.html
{% extends "app/base.html" %}

{% block content %}

{% load thumbnail %}
<!--POST start-->
<div class="container">
    <div class="row">
      <div class="col-md-10 col-sm-10">
        <h2 class="page-header">Post</h2>
          <section class="comment-list">
            <!-- First Comment -->


            {% for post in star_ordered_list %}
              <p>{{post.id}}</p>
              <p>{{post.fname}}</p>
              <p>{{post.fcontent}}</p>
              <p>{{post.price}}</p>
              <p style= "font-size:40" >rating : {{post.star}}</p>

              <hr>
            {% endfor %}
          </section>
      </div>
    </div>

  </div>

  <!--POST end-->
    
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-sm-10">
          <h2 class="page-header">Comments</h2>
            <section class="comment-list">
              <!-- First Comment -->
              {% for reply in reply_list %}
              <article class="row">
                <div class="col-md-2 col-sm-2 hidden-xs">
                  <figure class="thumbnail">
                    {% for corporation in corporation_list %}
                        {% if corporation.usr == reply.usr %}
                            {% if corporation.corp_logo %}
                                <img class="img-responsive" src="{{corporation.corp_logo.url}}" />
                            {% else %}
                                <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <figcaption class="text-center">{{reply.usr}}</figcaption>
                  </figure>
                </div>
                <div class="col-md-10 col-sm-10">
                  <div class="panel panel-default arrow left">
                    <div class="panel-body">
                      <header class="text-left">
                        <div class="comment-user"><i class="fa fa-user"></i><p>{{reply.usr}}</p></div>
                        <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
                      </header>
                      <div class="comment-post">
                        <p>
                          {{reply.message}}
                        </p>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-md-5 col-sm-6 star-post" align="center">
                        <span style="font-size:20px">User Grading</span>
                        <br>
                        <p>

                            {{ reply.star }}
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </p>
                        </div>
                        <div class="col-md-7 col-sm-7 image-post">
                        <div class="col-md-6 col-sm-6 before-image-post" align="center">
                        <span style="font-size:20px">Before Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.before_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                        <div class="col-md-6 col-sm-6 after-image-post" align="center">
                        <span style="font-size:20px">After Eat</span>
                        <br>
                        <p>
                            {% thumbnail reply.after_picture "150x150" crop="center" as thumb %}
                                <img src="{{ thumb.url }}">
                            {% endthumbnail %}
                        </p>
                        </div>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
              </article>
              {% endfor %}
            </section>
        </div>
      </div>
      <div class="row">
        <div class="col-md-offset-8 col-md-3 col-sm-offset-8 col-sm-3">
          <div class = "button_wrap" align="center">
            <a href="{% url 'app:reply_new' %}" class="button"> Add Comments</a>
          </div>
        </div>
      </div>
    </div>
    <hr/>


    {% endblock %}
  